# Generated by Django 4.1 on 2022-08-23 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record', models.IntegerField(verbose_name='Medical record number')),
                ('first_name', models.CharField(max_length=256, verbose_name='First name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of visit')),
                ('reason', models.TextField(max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_record.patients')),
            ],
        ),
    ]
