# Generated by Django 4.1 on 2022-08-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save_record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVs',
        ),
    ]
